# Generated by Django 3.1.7 on 2021-03-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Rápizes com seus apps'), ('lni-laptop-phone', 'Manutenção de Notbooks'), ('lni-cog', 'Engrenagem'), ('lni-leaf', 'Design Gráfico'), ('lni-layers', 'Multi-Plataforma'), ('lni-leaf', 'Recursos Humanos')], max_length=20, verbose_name='Icone'),
        ),
    ]
